// Generated from a local property revenue export. All guest identities and source identifiers
// are synthetic; company names, tax IDs, folio numbers, and payment remarks are excluded.

export const marketReservations = [
  {
    "id": "GH-R-2607-0001",
    "guest": "Adam Mitchell",
    "room": "102",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "08 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-11",
    "nights": 3,
    "status": "In house",
    "total": "1,121.83",
    "tax": "165.01",
    "paid": "1,121.83",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0002",
    "guest": "Alice Taylor",
    "room": "106",
    "roomType": "Presidential Suite City View",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "08 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-13",
    "nights": 5,
    "status": "In house",
    "total": "3,750.00",
    "tax": "551.70",
    "paid": "3,750.00",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0003",
    "guest": "Amelia Bennett",
    "room": "108",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "08 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-10",
    "nights": 2,
    "status": "In house",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0004",
    "guest": "Benjamin Foster",
    "room": "109",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "08 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-10",
    "nights": 2,
    "status": "In house",
    "total": "1,400.00",
    "tax": "205.50",
    "paid": "1,400.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0005",
    "guest": "Charlotte Hughes",
    "room": "202",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "08 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-13",
    "nights": 5,
    "status": "In house",
    "total": "2,242.78",
    "tax": "331.61",
    "paid": "2,242.78",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0006",
    "guest": "Chloe Price",
    "room": "209",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "08 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-11",
    "nights": 3,
    "status": "In house",
    "total": "2,250.00",
    "tax": "331.02",
    "paid": "2,250.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0007",
    "guest": "Daniel Ward",
    "room": "303",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "08 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-10",
    "nights": 2,
    "status": "In house",
    "total": "900.00",
    "tax": "133.08",
    "paid": "900.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0008",
    "guest": "David Clarke",
    "room": "308",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Room Only",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Other",
    "arrival": "08 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-13",
    "nights": 5,
    "status": "In house",
    "total": "1,906.40",
    "tax": "289.10",
    "paid": "1,906.40",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0009",
    "guest": "Eleanor Harris",
    "room": "309",
    "roomType": "Executive Suite",
    "rateType": "OTA Non-Refundable",
    "source": "Online Booking",
    "adults": 2,
    "children": 2,
    "paymentMethod": "mada",
    "arrival": "08 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-10",
    "nights": 2,
    "status": "In house",
    "total": "1,574.50",
    "tax": "238.76",
    "paid": "0.00",
    "balance": "1,574.50",
    "vip": false
  },
  {
    "id": "GH-R-2607-0010",
    "guest": "Emily Marshall",
    "room": "312",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Mastercard",
    "arrival": "08 Jul",
    "departure": "14 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-14",
    "nights": 6,
    "status": "In house",
    "total": "2,524.00",
    "tax": "372.46",
    "paid": "2,524.00",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0011",
    "guest": "Emma Scott",
    "room": "401",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "08 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-13",
    "nights": 5,
    "status": "In house",
    "total": "2,250.00",
    "tax": "332.70",
    "paid": "2,250.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0012",
    "guest": "Ethan Adams",
    "room": "408",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Cash",
    "arrival": "08 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-10",
    "nights": 2,
    "status": "In house",
    "total": "800.00",
    "tax": "117.92",
    "paid": "800.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0013",
    "guest": "Grace Evans",
    "room": "409",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Room Only",
    "source": "Online Booking",
    "adults": 4,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "08 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-10",
    "nights": 2,
    "status": "In house",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0014",
    "guest": "Hannah Howard",
    "room": "501",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "08 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-13",
    "nights": 5,
    "status": "In house",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0015",
    "guest": "Henry Parker",
    "room": "508",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Travel Agent",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Mastercard",
    "arrival": "08 Jul",
    "departure": "15 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-15",
    "nights": 7,
    "status": "In house",
    "total": "2,860.00",
    "tax": "421.81",
    "paid": "2,860.00",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0016",
    "guest": "Isabella Walker",
    "room": "601",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "08 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-11",
    "nights": 3,
    "status": "In house",
    "total": "1,200.00",
    "tax": "179.46",
    "paid": "1,200.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0017",
    "guest": "Jack Carter",
    "room": "602",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 2,
    "children": 1,
    "paymentMethod": "Mastercard",
    "arrival": "08 Jul",
    "departure": "14 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-14",
    "nights": 6,
    "status": "In house",
    "total": "3,018.70",
    "tax": "445.46",
    "paid": "3,018.70",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0018",
    "guest": "James Hall",
    "room": "606",
    "roomType": "Presidential Suite City View",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "08 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-13",
    "nights": 5,
    "status": "In house",
    "total": "3,750.00",
    "tax": "551.70",
    "paid": "3,750.00",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0019",
    "guest": "Jessica Lewis",
    "room": "302",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "OTA Room Only",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "07 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-07",
    "departureISO": "2026-07-10",
    "nights": 3,
    "status": "In house",
    "total": "1,462.52",
    "tax": "221.79",
    "paid": "1,462.52",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0020",
    "guest": "Leo Roberts",
    "room": "605",
    "roomType": "Deluxe King Room City View",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "07 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-07",
    "departureISO": "2026-07-10",
    "nights": 3,
    "status": "In house",
    "total": "900.00",
    "tax": "131.40",
    "paid": "900.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0021",
    "guest": "Lucy Wilson",
    "room": "101",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Mastercard",
    "arrival": "09 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-13",
    "nights": 4,
    "status": "Arriving",
    "total": "2,241.90",
    "tax": "333.16",
    "paid": "2,241.90",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0022",
    "guest": "Matthew Cooper",
    "room": "107",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Mastercard",
    "arrival": "09 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-13",
    "nights": 4,
    "status": "Arriving",
    "total": "2,241.90",
    "tax": "336.60",
    "paid": "2,241.90",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0023",
    "guest": "Mia Hill",
    "room": "112",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 2,
    "children": 2,
    "paymentMethod": "Cash",
    "arrival": "09 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-12",
    "nights": 3,
    "status": "Arriving",
    "total": "2,090.32",
    "tax": "311.88",
    "paid": "2,090.32",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0024",
    "guest": "Nathan Morgan",
    "room": "201",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "09 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-10",
    "nights": 1,
    "status": "Arriving",
    "total": "400.00",
    "tax": "60.65",
    "paid": "400.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0025",
    "guest": "Noah Turner",
    "room": "203",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "09 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-11",
    "nights": 2,
    "status": "Arriving",
    "total": "800.00",
    "tax": "119.64",
    "paid": "800.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0026",
    "guest": "Oliver Brooks",
    "room": "206",
    "roomType": "Presidential Suite City View",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "09 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-10",
    "nights": 1,
    "status": "Arriving",
    "total": "800.00",
    "tax": "117.92",
    "paid": "800.00",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0027",
    "guest": "Olivia Green",
    "room": "212",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Room Only",
    "source": "Online Booking",
    "adults": 2,
    "children": 2,
    "paymentMethod": "mada",
    "arrival": "09 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-13",
    "nights": 4,
    "status": "Arriving",
    "total": "2,111.36",
    "tax": "320.17",
    "paid": "2,111.36",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0028",
    "guest": "Samuel King",
    "room": "301",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Non-Refundable",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "09 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-13",
    "nights": 4,
    "status": "Arriving",
    "total": "1,929.71",
    "tax": "290.49",
    "paid": "1,929.71",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0029",
    "guest": "Sophie Reed",
    "room": "306",
    "roomType": "Presidential Suite City View",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 3,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "09 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-10",
    "nights": 1,
    "status": "Arriving",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0030",
    "guest": "Thomas Watson",
    "room": "307",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Mastercard",
    "arrival": "09 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-13",
    "nights": 4,
    "status": "Arriving",
    "total": "2,241.90",
    "tax": "336.60",
    "paid": "2,241.90",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0031",
    "guest": "Victoria Collins",
    "room": "402",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "09 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-11",
    "nights": 2,
    "status": "Arriving",
    "total": "840.00",
    "tax": "123.98",
    "paid": "840.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0032",
    "guest": "William Hayes",
    "room": "406",
    "roomType": "Presidential Suite City View",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "09 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-10",
    "nights": 1,
    "status": "Arriving",
    "total": "750.00",
    "tax": "113.74",
    "paid": "750.00",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0033",
    "guest": "Adam Morgan",
    "room": "407",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "09 Jul",
    "departure": "23 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-23",
    "nights": 14,
    "status": "Arriving",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0034",
    "guest": "Alice Turner",
    "room": "412",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "09 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-10",
    "nights": 1,
    "status": "Arriving",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0035",
    "guest": "Amelia Brooks",
    "room": "502",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "OTA Non-Refundable",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Mastercard",
    "arrival": "09 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-11",
    "nights": 2,
    "status": "Arriving",
    "total": "1,165.37",
    "tax": "176.72",
    "paid": "1,165.37",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0036",
    "guest": "Benjamin Green",
    "room": "503",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "09 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-10",
    "nights": 1,
    "status": "Arriving",
    "total": "400.00",
    "tax": "60.65",
    "paid": "400.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0037",
    "guest": "Charlotte King",
    "room": "505",
    "roomType": "Deluxe King Room City View",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "09 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-10",
    "nights": 1,
    "status": "Arriving",
    "total": "300.00",
    "tax": "45.49",
    "paid": "300.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0038",
    "guest": "Chloe Reed",
    "room": "507",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "OTA Non-Refundable",
    "source": "Online Booking",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Mastercard",
    "arrival": "09 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-11",
    "nights": 2,
    "status": "Arriving",
    "total": "1,165.37",
    "tax": "176.72",
    "paid": "1,165.37",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0039",
    "guest": "Daniel Watson",
    "room": "509",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "09 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-13",
    "nights": 4,
    "status": "Arriving",
    "total": "3,000.00",
    "tax": "441.36",
    "paid": "3,000.00",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0040",
    "guest": "David Collins",
    "room": "512",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Cash",
    "arrival": "09 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-11",
    "nights": 2,
    "status": "Arriving",
    "total": "840.00",
    "tax": "123.98",
    "paid": "840.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0041",
    "guest": "Eleanor Hayes",
    "room": "603",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "09 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-11",
    "nights": 2,
    "status": "Arriving",
    "total": "800.00",
    "tax": "121.30",
    "paid": "800.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0042",
    "guest": "Emily Mitchell",
    "room": "607",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "09 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-11",
    "nights": 2,
    "status": "Arriving",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0043",
    "guest": "Emma Taylor",
    "room": "609",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Travel Agent",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "09 Jul",
    "departure": "10 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-10",
    "nights": 1,
    "status": "Arriving",
    "total": "700.00",
    "tax": "102.75",
    "paid": "700.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0044",
    "guest": "Ethan Bennett",
    "room": "612",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "09 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-09",
    "departureISO": "2026-07-11",
    "nights": 2,
    "status": "Arriving",
    "total": "840.00",
    "tax": "125.68",
    "paid": "840.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0045",
    "guest": "Grace Foster",
    "room": "101",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "08 Jul",
    "departure": "09 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-09",
    "nights": 1,
    "status": "Due out",
    "total": "508.36",
    "tax": "76.24",
    "paid": "508.36",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0046",
    "guest": "Hannah Hughes",
    "room": "112",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Mastercard",
    "arrival": "08 Jul",
    "departure": "09 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-09",
    "nights": 1,
    "status": "Due out",
    "total": "595.15",
    "tax": "88.55",
    "paid": "595.15",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0047",
    "guest": "Henry Price",
    "room": "201",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Cash",
    "arrival": "08 Jul",
    "departure": "09 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-09",
    "nights": 1,
    "status": "Due out",
    "total": "400.00",
    "tax": "60.65",
    "paid": "400.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0048",
    "guest": "Isabella Ward",
    "room": "412",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Travel Agent",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "08 Jul",
    "departure": "09 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-09",
    "nights": 1,
    "status": "Due out",
    "total": "450.00",
    "tax": "66.54",
    "paid": "450.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0049",
    "guest": "Jack Clarke",
    "room": "505",
    "roomType": "Deluxe King Room City View",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "08 Jul",
    "departure": "09 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-09",
    "nights": 1,
    "status": "Due out",
    "total": "300.00",
    "tax": "45.49",
    "paid": "300.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0050",
    "guest": "James Harris",
    "room": "512",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "08 Jul",
    "departure": "09 Jul",
    "arrivalISO": "2026-07-08",
    "departureISO": "2026-07-09",
    "nights": 1,
    "status": "Due out",
    "total": "390.00",
    "tax": "59.14",
    "paid": "390.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0051",
    "guest": "Jessica Marshall",
    "room": "306",
    "roomType": "Presidential Suite City View",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 3,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "07 Jul",
    "departure": "09 Jul",
    "arrivalISO": "2026-07-07",
    "departureISO": "2026-07-09",
    "nights": 2,
    "status": "Due out",
    "total": "1,524.91",
    "tax": "226.16",
    "paid": "1,524.91",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0052",
    "guest": "Leo Scott",
    "room": "307",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Corporate Bed & Breakfast",
    "source": "Corporate",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Other",
    "arrival": "07 Jul",
    "departure": "09 Jul",
    "arrivalISO": "2026-07-07",
    "departureISO": "2026-07-09",
    "nights": 2,
    "status": "Due out",
    "total": "760.00",
    "tax": "111.84",
    "paid": "760.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0053",
    "guest": "Lucy Adams",
    "room": "609",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "Mastercard",
    "arrival": "07 Jul",
    "departure": "09 Jul",
    "arrivalISO": "2026-07-07",
    "departureISO": "2026-07-09",
    "nights": 2,
    "status": "Due out",
    "total": "1,300.00",
    "tax": "190.34",
    "paid": "1,300.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0054",
    "guest": "Matthew Evans",
    "room": "109",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "15 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-15",
    "nights": 5,
    "status": "Confirmed",
    "total": "2,700.00",
    "tax": "409.43",
    "paid": "2,700.00",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0055",
    "guest": "Mia Howard",
    "room": "109",
    "roomType": "Executive Suite",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 4,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "10 Jul",
    "departure": "16 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-16",
    "nights": 6,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0056",
    "guest": "Nathan Parker",
    "room": "201",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "14 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-14",
    "nights": 4,
    "status": "Confirmed",
    "total": "1,794.22",
    "tax": "265.28",
    "paid": "1,794.22",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0057",
    "guest": "Noah Walker",
    "room": "201",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Non-Refundable",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "10 Jul",
    "departure": "15 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-15",
    "nights": 5,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0058",
    "guest": "Oliver Carter",
    "room": "205",
    "roomType": "Deluxe King Room City View",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "15 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-15",
    "nights": 5,
    "status": "Confirmed",
    "total": "1,750.00",
    "tax": "265.35",
    "paid": "1,750.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0059",
    "guest": "Olivia Hall",
    "room": "206",
    "roomType": "Presidential Suite City View",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "17 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-17",
    "nights": 7,
    "status": "Confirmed",
    "total": "5,696.22",
    "tax": "840.07",
    "paid": "5,696.22",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0060",
    "guest": "Samuel Lewis",
    "room": "208",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Room Only",
    "source": "Wholesaler",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "10 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-11",
    "nights": 1,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0061",
    "guest": "Sophie Roberts",
    "room": "208",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Bed & Breakfast",
    "source": "Wholesaler",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Other",
    "arrival": "10 Jul",
    "departure": "15 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-15",
    "nights": 5,
    "status": "Confirmed",
    "total": "2,250.00",
    "tax": "332.70",
    "paid": "2,250.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0062",
    "guest": "Thomas Wilson",
    "room": "302",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "OTA Room Only",
    "source": "Online Booking",
    "adults": 2,
    "children": 1,
    "paymentMethod": "Unpaid",
    "arrival": "10 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-12",
    "nights": 2,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0063",
    "guest": "Victoria Cooper",
    "room": "302",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Travel Agent",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "15 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-15",
    "nights": 5,
    "status": "Confirmed",
    "total": "2,250.00",
    "tax": "332.70",
    "paid": "2,250.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0064",
    "guest": "William Hill",
    "room": "303",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Travel Agent",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "15 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-15",
    "nights": 5,
    "status": "Confirmed",
    "total": "2,250.00",
    "tax": "332.70",
    "paid": "2,250.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0065",
    "guest": "Adam Parker",
    "room": "306",
    "roomType": "Presidential Suite City View",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 3,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "10 Jul",
    "departure": "17 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-17",
    "nights": 7,
    "status": "Confirmed",
    "total": "5,250.00",
    "tax": "778.26",
    "paid": "5,250.00",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0066",
    "guest": "Alice Walker",
    "room": "309",
    "roomType": "Executive Suite",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "16 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-16",
    "nights": 6,
    "status": "Confirmed",
    "total": "4,574.74",
    "tax": "673.38",
    "paid": "4,574.74",
    "balance": "0.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0067",
    "guest": "Amelia Carter",
    "room": "406",
    "roomType": "Presidential Suite City View",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "17 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-17",
    "nights": 7,
    "status": "Confirmed",
    "total": "5,250.00",
    "tax": "772.38",
    "paid": "4,500.00",
    "balance": "750.00",
    "vip": true
  },
  {
    "id": "GH-R-2607-0068",
    "guest": "Benjamin Hall",
    "room": "407",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-11",
    "nights": 1,
    "status": "Confirmed",
    "total": "400.00",
    "tax": "60.65",
    "paid": "400.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0069",
    "guest": "Charlotte Lewis",
    "room": "408",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-13",
    "nights": 3,
    "status": "Confirmed",
    "total": "1,345.67",
    "tax": "198.96",
    "paid": "1,345.67",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0070",
    "guest": "Chloe Roberts",
    "room": "409",
    "roomType": "Executive Suite",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 4,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "10 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-12",
    "nights": 2,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0071",
    "guest": "Daniel Wilson",
    "room": "409",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "10 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-12",
    "nights": 2,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0072",
    "guest": "David Cooper",
    "room": "409",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "10 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-12",
    "nights": 2,
    "status": "Confirmed",
    "total": "1,600.00",
    "tax": "238.39",
    "paid": "1,600.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0073",
    "guest": "Eleanor Hill",
    "room": "412",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-11",
    "nights": 1,
    "status": "Confirmed",
    "total": "430.00",
    "tax": "65.21",
    "paid": "430.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0074",
    "guest": "Emily Morgan",
    "room": "503",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-12",
    "nights": 2,
    "status": "Confirmed",
    "total": "760.00",
    "tax": "115.26",
    "paid": "760.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0075",
    "guest": "Emma Turner",
    "room": "505",
    "roomType": "Deluxe King Room City View",
    "rateType": "OTA Room Only",
    "source": "Wholesaler",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Other",
    "arrival": "10 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-12",
    "nights": 2,
    "status": "Confirmed",
    "total": "600.00",
    "tax": "90.98",
    "paid": "600.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0076",
    "guest": "Ethan Brooks",
    "room": "605",
    "roomType": "Deluxe King Room City View",
    "rateType": "OTA Room Only",
    "source": "Wholesaler",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Other",
    "arrival": "10 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-11",
    "nights": 1,
    "status": "Confirmed",
    "total": "300.00",
    "tax": "45.49",
    "paid": "300.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0077",
    "guest": "Grace Green",
    "room": "608",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "15 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-15",
    "nights": 5,
    "status": "Confirmed",
    "total": "2,100.00",
    "tax": "309.95",
    "paid": "2,100.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0078",
    "guest": "Hannah King",
    "room": "609",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "10 Jul",
    "departure": "11 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-11",
    "nights": 1,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0079",
    "guest": "Henry Reed",
    "room": "609",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "10 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-10",
    "departureISO": "2026-07-13",
    "nights": 3,
    "status": "Confirmed",
    "total": "2,100.00",
    "tax": "308.25",
    "paid": "2,100.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0080",
    "guest": "Isabella Watson",
    "room": "102",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "11 Jul",
    "departure": "14 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-14",
    "nights": 3,
    "status": "Confirmed",
    "total": "1,350.00",
    "tax": "202.20",
    "paid": "1,350.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0081",
    "guest": "Jack Collins",
    "room": "103",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "11 Jul",
    "departure": "16 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-16",
    "nights": 5,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0082",
    "guest": "James Hayes",
    "room": "103",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "11 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-13",
    "nights": 2,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0083",
    "guest": "Jessica Mitchell",
    "room": "103",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Cash",
    "arrival": "11 Jul",
    "departure": "14 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-14",
    "nights": 3,
    "status": "Confirmed",
    "total": "1,290.00",
    "tax": "190.50",
    "paid": "1,290.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0084",
    "guest": "Leo Taylor",
    "room": "203",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "11 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-12",
    "nights": 1,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0085",
    "guest": "Lucy Bennett",
    "room": "203",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "11 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-12",
    "nights": 1,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0086",
    "guest": "Matthew Foster",
    "room": "203",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "11 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-12",
    "nights": 1,
    "status": "Confirmed",
    "total": "500.00",
    "tax": "74.12",
    "paid": "500.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0087",
    "guest": "Mia Hughes",
    "room": "209",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "11 Jul",
    "departure": "18 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-18",
    "nights": 7,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0088",
    "guest": "Nathan Price",
    "room": "209",
    "roomType": "Executive Suite",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 4,
    "children": 0,
    "paymentMethod": "Visa",
    "arrival": "11 Jul",
    "departure": "14 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-14",
    "nights": 3,
    "status": "Confirmed",
    "total": "2,100.00",
    "tax": "308.25",
    "paid": "2,100.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0089",
    "guest": "Noah Ward",
    "room": "402",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "OTA Bed & Breakfast",
    "source": "Online Booking",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "11 Jul",
    "departure": "13 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-13",
    "nights": 2,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0090",
    "guest": "Oliver Clarke",
    "room": "402",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "11 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-12",
    "nights": 1,
    "status": "Confirmed",
    "total": "425.00",
    "tax": "62.22",
    "paid": "425.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0091",
    "guest": "Olivia Harris",
    "room": "407",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "11 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-12",
    "nights": 1,
    "status": "Confirmed",
    "total": "400.00",
    "tax": "60.65",
    "paid": "400.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0092",
    "guest": "Samuel Marshall",
    "room": "412",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "11 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-12",
    "nights": 1,
    "status": "Confirmed",
    "total": "400.00",
    "tax": "58.96",
    "paid": "400.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0093",
    "guest": "Sophie Scott",
    "room": "502",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "11 Jul",
    "departure": "19 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-19",
    "nights": 8,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0094",
    "guest": "Thomas Adams",
    "room": "502",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Room Only",
    "source": "Direct / Walk-in",
    "adults": 1,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "11 Jul",
    "departure": "12 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-12",
    "nights": 1,
    "status": "Confirmed",
    "total": "400.00",
    "tax": "60.65",
    "paid": "400.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0095",
    "guest": "Victoria Evans",
    "room": "507",
    "roomType": "Deluxe Junior Suite Twin",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "mada",
    "arrival": "11 Jul",
    "departure": "15 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-15",
    "nights": 4,
    "status": "Confirmed",
    "total": "1,600.00",
    "tax": "235.83",
    "paid": "1,600.00",
    "balance": "0.00",
    "vip": false
  },
  {
    "id": "GH-R-2607-0096",
    "guest": "William Howard",
    "room": "512",
    "roomType": "Deluxe Junior Suite King Bed",
    "rateType": "Walk-in Bed & Breakfast",
    "source": "Direct / Walk-in",
    "adults": 2,
    "children": 0,
    "paymentMethod": "Unpaid",
    "arrival": "11 Jul",
    "departure": "17 Jul",
    "arrivalISO": "2026-07-11",
    "departureISO": "2026-07-17",
    "nights": 6,
    "status": "Confirmed",
    "total": "0.00",
    "tax": "0.00",
    "paid": "0.00",
    "balance": "0.00",
    "vip": false
  }
];

export const marketSummary = {
  "sourceRowsReviewed": 856,
  "sanitizedReservations": 96,
  "businessDate": "2026-07-09",
  "sourceMix": {
    "Direct / Walk-in": 59,
    "Online Booking": 27,
    "Travel Agent": 5,
    "Wholesaler": 4,
    "Corporate": 1
  },
  "rateMix": {
    "Walk-in Bed & Breakfast": 44,
    "Walk-in Room Only": 21,
    "OTA Bed & Breakfast": 18,
    "OTA Room Only": 7,
    "OTA Non-Refundable": 5,
    "Corporate Bed & Breakfast": 1
  },
  "roomMix": {
    "Deluxe Junior Suite King Bed": 42,
    "Deluxe Junior Suite Twin": 22,
    "Executive Suite": 17,
    "Presidential Suite City View": 9,
    "Deluxe King Room City View": 6
  },
  "statusMix": {
    "Confirmed": 43,
    "Arriving": 24,
    "In house": 20,
    "Due out": 9
  },
  "revenue": {
    "gross": "1,197,296.80",
    "roomCharges": "836,440.24",
    "breakfast": "140,247.04",
    "dinner": "16,487.26",
    "transportation": "4,695.66",
    "vat": "156,164.78",
    "municipalityFee": "20,909.66"
  },
  "payments": {
    "mada": "595,417.48",
    "visa": "207,617.30",
    "mastercard": "91,137.36",
    "cash": "95,239.46",
    "bankTransfer": "30,611.32",
    "gccnet": "9,045.50",
    "americanExpress": "5,600.00"
  }
};
